[package]
name = "wampire"
version = "0.1.2"
authors = ["Golem Factory <contact@golem.network>", "Dudochkin Victor <dudochkin.victor@gmail.com>", "Daniel Yule <yule@cs.dal.ca>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ohyo-io/wampire"
documentation = "https://github.com/ohyo-io/wampire"
homepage = "https://github.com/ohyo-io/wampire"
description = "A WAMPv2 client and router implenting the basic WAMP profile"
keywords = ["rpc", "pubsub", "wamp", "wamp2"]
categories = ["network-programming", "web-programming", "web-programming::websocket"]

[lib]
name = "wampire"
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7"
log = "0.4"
env_logger = "0.5"
ws = "0.7"
rmp = "0.8"
rmp-serde = "0.13"
rand = "0.5.0-pre.1"
eventual = "0.1.7"
itertools = "0.7"
argparse = "0.2.1"

[dependencies.openssl]
version = "0.9"
optional = true

[features]
default-features = []
ssl = ["ws/ssl", "openssl"]
